apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: dankpods.net-ingress
spec:
  entryPoints:
   - web
  routes:
    - match: Host(`dev.dankpods.net`)
      kind: Rule
      services:
      - name: dankpods-server
        port: 80

---

apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: dankpods.net-secure-ingress
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`dev.dankpods.net`)
      services:
        - name: dankpods-server
          port: 80
  tls:
    secretName: dev.dankpods.net-tls

---

apiVersion: v1
kind: Service
metadata:
  name: dankpods-server
spec:
  selector:
    app: dankpods-server
  ports:
  - protocol: "TCP"
    port: 80
    targetPort: 80
  type: ClusterIP

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: dankpods-server
spec:
  selector:
    matchLabels:
      app: dankpods-server
  replicas: 1
  template:
    metadata:
      labels:
        app: dankpods-server
    spec:
      containers:
      - name: dankpods
        image: harbor.dotglitch.dev/library/dankpods:latest
        ports:
        - containerPort: 80
      imagePullSecrets:
      - name: harbor-key

---

apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: dev.dankpods.net
spec:
  commonName: dev.dankpods.net
  dnsNames:
    - dev.dankpods.net
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt-prod
  secretName: dev.dankpods.net-tls


